Repository hfmaracay/api_laravel_hfmaracay, pull requests merged in 2019-10, with the labels that each got.

#26 CRUD de Usuarios [Read]
  app/Http/Controllers/Admin/UserController.php
  app/Http/Controllers/AuthController.php
  app/Http/Kernel.php
  app/Http/Requests/Users/CreateUserRequest.php
  app/Queries/QueryFilter.php
  app/Queries/UserFilter.php
  app/User.php
  routes/api.php
Labels: Hacktoberfest, enhancement, good first issue

#27 Delete de usuarios listo
  app/Http/Controllers/Admin/UserController.php
  routes/api.php
Labels: Hacktoberfest, enhancement, good first issue

#29 Error de sintaxis en routes api
  routes/api.php
Labels: Hacktoberfest, bug, good first issue

#30 Correcciones simples
  .gitignore
  app/Area.php
  app/Country.php
  app/Http/Controllers/Admin/UserController.php
  app/Http/Controllers/AuthController.php
  app/Http/Middleware/Authenticate.php
  app/Http/Requests/Users/CreateUserRequest.php
  app/Providers/RouteServiceProvider.php
  app/Queries/QueryFilter.php
  app/Queries/UserFilter.php
  app/User.php
  routes/api.php
Labels: Hacktoberfest, good first issue

#33 Esqueleto para el crud de eventos
  app/Event.php
  app/Http/Controllers/EventController.php
  database/factories/EventFactory.php
  database/migrations/2019_10_14_125054_create_events_table.php
  routes/api.php
Labels: Hacktoberfest, enhancement, good first issue

#34 Corregido error de sintaxis llave foranea en Eventos-Pictures
  app/Http/Controllers/Admin/AreaController.php
  database/migrations/2019_10_10_130747_create_pictures_table.php
  database/migrations/2019_10_14_125054_create_events_table.php
Labels: Hacktoberfest, bug, good first issue

#35 CRUD Areas
  app/Http/Controllers/Admin/AreaController.php
  app/Http/Controllers/Admin/EventController.php
  app/Http/Controllers/Admin/PicturesController.php
  app/Http/Controllers/Admin/UserController.php
  routes/api.php
Labels: Hacktoberfest, enhancement, good first issue

#36 Show pictures created
  app/Http/Controllers/Admin/PicturesController.php
  app/Pictures.php
  app/Queries/PictureFilter.php
Labels: Hacktoberfest, enhancement, good first issue

#37 CRUD Countries
  app/Http/Controllers/Admin/CountryController.php
Labels: Hacktoberfest, enhancement, good first issue
